This bot is perfect, release it already!
ilyabelow/cool_and_new_vk_bot pull request #1
Opened 2019-05-11 20:58 UTC by ilyabelow

2019-05-12 11:49 UTC, alexeyqu commented on .gitignore
> +*token.txt
empty line

2019-05-12 11:52 UTC, alexeyqu commented on bot.py
> +def iterate_random_id():
Есть опасность забыть проинициализировать random_id.

2019-05-12 11:52 UTC, alexeyqu commented on bot.py
> +def iterate_random_id():
Ну и без global можно обойтись.

2019-05-12 11:55 UTC, alexeyqu commented on bot.py
> +        handle_weather_request(event, event.text[len('Покажи погоду в городе '):])
`Покажи погоду в городе ` это серьёзная константа получается.
Давай отдельным методом доставать город из запроса?
Кстати, в Вк есть /command команды как в Тг?
Мб вместо поиска нужного текста просто сделать разные команды?

2019-05-12 11:56 UTC, alexeyqu commented on bot.py
> +    # TODO what will happen if current city is not stated?
Ловить исключение и отсылать юзеру текст, что у него нет города.
Опционально -- фолбэчиться на Москву/Бобруйск/Челябинск.

2019-05-12 12:03 UTC, alexeyqu commented on bot.py
> +                     message="Сложно",
^_^

2019-05-12 12:03 UTC, alexeyqu commented on bot.py
> +                                 message="Уууу, редактируешь >:(",
^___^

2019-05-12 12:06 UTC, alexeyqu commented on bot.py
> +        token = file.readline()
А давай не читать токен заново на каждый запрос?
Вместе с несколькими предыдущими комментариями: нужен класс для хранения состояния: random_id, токенов и т.д.

2019-05-12 12:07 UTC, alexeyqu requested changes
comments

2019-05-12 15:51 UTC, ilyabelow commented on bot.py
> +def iterate_random_id():
Вы предлагаете инициализировать внутри функции при её первом вызове? И как без глобала делать..?

2019-05-12 15:55 UTC, ilyabelow commented on bot.py
> +        handle_weather_request(event, event.text[len('Покажи погоду в городе '):])
По сути константа Покажи погоду в городе - это и есть константа. Функция для поиска города в запросе должна получается как-то семантически разбирать предложение чтобы понять какой набор слов является гордом, что звучит как-то сложно. Команд через / в тут нет, ВК в этом смысле очень примитивный

2019-05-12 15:56 UTC, ilyabelow commented on bot.py
> +                     message="Сложно",
В идеале сделать поиск ругательств чтобы бот ругался в ответ

2019-05-13 07:51 UTC, ilyabelow commented on .gitignore
> +*token.txt
fixed

2019-05-13 07:54 UTC, ilyabelow commented on bot.py
> +                                 message="Уууу, редактируешь >:(",
Ага

2019-05-13 07:54 UTC, ilyabelow commented on bot.py
> +        token = file.readline()
Хорошая идея, исправлю

2019-05-13 08:41 UTC, ilyabelow commented on bot.py
> +        token = file.readline()
Done

2019-05-15 09:21 UTC, alexeyqu commented on bot.py
> +        handle_weather_request(event, event.text[len('Покажи погоду в городе '):])
:(

2019-05-15 09:22 UTC, alexeyqu commented on bot.py
> +def iterate_random_id():
Да нет, просто упихать state в класс, который инициализировать в начале. И там же хранить этот каунтер

2019-05-15 09:23 UTC, alexeyqu commented on bot.py
> +        token = file.readline()
Точно?
Этот токен можно положить в тот же state

2019-05-18 09:51 UTC, alexeyqu commented on const.py
> +    weather_token = file.readline()
alright

2019-05-18 10:34 UTC, ilyabelow commented on bot.py
> +def iterate_random_id():
Можно и так

2019-05-18 12:33 UTC, ilyabelow commented on bot.py
> +    # TODO what will happen if current city is not stated?
Теперь бот шлёт юзера куда подальше!

2019-05-28 18:27 UTC, merged